Repository Step3-kakao-tech-campus/Team4_BE, pull requests merged in 2023-11, with the labels that each got.

#95 Break Circular Reference Between StoreService and LikeStoreService
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/CreateLikeStoreUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
Labels: Bugfix, Feature

#97 리뷰 및 리뷰 좋아요 기능 보완
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
Labels: Feature, API, Refactor

#102 Add Query Parameter Validation & Exception Handling Logic
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/ErrorHandlingController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/application.yml
Labels: Bugfix, Feature, API

#103 Improve user authentication and implement logout and token reissue endpoints
  matgpt/src/main/java/com/ktc/matgpt/auth/AuthController.java
  matgpt/src/main/java/com/ktc/matgpt/auth/AuthService.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorCode.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReview.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenDto.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/KakaoOAuth2UserInfo.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/LocaleConverter.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/RefreshToken.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/User.java
  matgpt/src/main/java/com/ktc/matgpt/user/repository/RefreshTokenRepository.java
  matgpt/src/main/java/com/ktc/matgpt/user/repository/UserRepository.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/RefreshTokenService.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/custom.sql
Labels: Feature, API, Refactor

#108 리뷰 테스트 코드 작성, 리뷰 좋아요 구현
  matgpt/src/main/java/com/ktc/matgpt/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReview.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/utils/BaseEntity.java
  matgpt/src/main/java/com/ktc/matgpt/utils/BaseTimeEntity.java
  matgpt/src/main/java/com/ktc/matgpt/utils/UserAuditorAware.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Refactor

#110 Review 테스트 코드 완료, 리뷰 좋아요 기능 완료
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/CreateLikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Test

#111 리뷰/리뷰 좋아요 목록 조회 페이지네이션 및 응답 DTO 수정, 관련 테스트 코드 수정
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorCode.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/CreateLikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Feature, API, Test, Need Test Code

#112 마이페이지 테스트 코드 작성
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorCode.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/tag/Tag.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/TestHelper.java
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Test, Refactor

#119 리뷰 조회, 임시저장 테스트 오류 해결
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Bugfix, Test, Refactor

#120 리뷰 생성/삭제 시 관련 Entity 업데이트 로직 추가
  matgpt/src/main/java/com/ktc/matgpt/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/food/dto/FoodDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/tag/TagService.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Feature, API, Test, Refactor

#122 Review 리팩토링, 관련 엔티티 및 DTO 수정
  matgpt/src/main/java/com/ktc/matgpt/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/food/dto/FoodDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Feature, API, Test, Refactor

#124 리뷰 목록 조회 페이지네이션 버그 수정, 개선
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
Labels: Bugfix, Refactor

#125 s3 삭제 구현
  matgpt/src/main/java/com/ktc/matgpt/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
Labels: Feature, Refactor

#126 즐겨찾기한 음식점 LikeStore 목록 조회 페이지네이션 추가 및 응답 형식 수정
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreService.java
Labels: Feature, API, Refactor

#130 Review, LikeReview 리팩토링 및 관련 클래스 구현
  matgpt/src/main/java/com/ktc/matgpt/image/ImageJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/utils/CursorRequest.java
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Feature, Test, Refactor

#133 s3 imageUrl 저장, s3 image 삭제 기능 보완
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/domain/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorMessage.java
Labels: Bugfix, Feature, Refactor

#136 배포 환경설정 완료
  Dockerfile
  goorm.manifest
  k8s/backend.yaml
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
Labels: Production

#139 배포 환경설정 적용
  .gitignore
  Dockerfile
  goorm.manifest
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  matgpt/.gitignore
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/config/DatabaseInitializer.java
  matgpt/src/main/java/com/ktc/matgpt/config/HttpConnectionProxyConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/RestTemplateConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/domain/image/ImageService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/application-prod.yml
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/application.yml
  matgpt/src/main/resources/custom_prod.sql
  matgpt/src/main/resources/matgpt_backup.sql
Labels: Feature

#141 Enhancements in Coin Management and API Response Standardization
  matgpt/src/main/java/com/ktc/matgpt/domain/chatgpt/service/GptOrderGuidanceService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/Coin.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/controller/UserController.java
  matgpt/src/main/java/com/ktc/matgpt/security/auth/AuthController.java
  matgpt/src/main/java/com/ktc/matgpt/security/auth/AuthService.java
  matgpt/src/main/resources/custom.sql
Labels: Refactor

#142 Add S3 Image Upload Processing Logic in UserService
  matgpt/src/main/java/com/ktc/matgpt/domain/user/controller/UserController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/dto/UserDto.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/service/UserService.java
Labels: Feature, API

#143 Feature/exception
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/auth/UserAlreadyExistsException.java
  matgpt/src/main/java/com/ktc/matgpt/security/auth/AuthService.java
Labels: Bugfix, Refactor

#145 User 이미지 저장 로직 수정, Tag 삭제 수정
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/domain/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/tag/TagJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/controller/UserController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/service/UserService.java
Labels: Bugfix, Feature, Refactor

#144 Coin 기능 리팩토링 및 유효성 검사
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/controller/CoinController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/dto/CoinRequest.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/Coin.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinEarningHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinUsageHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/repository/CoinUsageHistoryRepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/service/CoinHistoryService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/service/CoinService.java
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorMessage.java
Labels: Feature

#146 userProfileImage 업로드 오류 수정
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
Labels: Bugfix

#148 Local Main -> Origin Main
  k8s/backend.yaml
  k8s/configs/init.sql
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/domain/chatgpt/service/GptOrderGuidanceService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/controller/CoinController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/dto/CoinRequest.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/Coin.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinEarningHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/entity/CoinUsageHistory.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/repository/CoinEarningHistoryRepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/repository/CoinUsageHistoryRepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/service/CoinHistoryService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/service/CoinService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/food/FoodController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeReview/LikeReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeStore/LikeStoreResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeStore/LikeStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/likeStore/LikeStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/usecase/LikeReviewUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/domain/like/usecase/LikeStoreUseCase.java
  matgpt/src/main/java/com/ktc/matgpt/domain/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/domain/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/tag/TagJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/controller/UserController.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/dto/UserDto.java
  matgpt/src/main/java/com/ktc/matgpt/domain/user/service/UserService.java
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorMessage.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/auth/UserAlreadyExistsException.java
  matgpt/src/main/java/com/ktc/matgpt/security/auth/AuthController.java
  matgpt/src/main/java/com/ktc/matgpt/security/auth/AuthService.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/resources/application-prod.yml
  matgpt/src/main/resources/custom.sql
  matgpt/src/test/java/com/ktc/matgpt/likeReview/LikeReviewRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
Labels: Production

#147 테스트 오류 수정
  matgpt/src/main/resources/custom_modified.sql
  matgpt/src/test/java/com/ktc/matgpt/coin/CoinControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/likeReview/LikeReviewRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
Labels: Test

#150 [Main -> Weekly] Readme 파일 업데이트
  README.md
  assets/erd.png
  assets/krampoline-prod-process.png
  matgpt/src/main/java/com/ktc/matgpt/domain/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/domain/chatgpt/service/GptOrderGuidanceService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/repository/CoinEarningHistoryRepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/repository/CoinUsageHistoryRepository.java
  matgpt/src/main/java/com/ktc/matgpt/domain/coin/service/CoinHistoryService.java
  matgpt/src/main/java/com/ktc/matgpt/domain/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorMessage.java
Labels: Docs, Production

#151 [최종 제출] 배포 완료
  README.md
Labels: Production
