Repository Step3-kakao-tech-campus/Team4_BE, pull requests merged in 2023-10, with the labels that each got.

#15 프로젝트 초기 설정 및 환경 구축 업데이트
  matgpt/src/main/resources/application.yml
Labels: Docs, Feature

#16 Implementation and Update of OAuth2 and JWT Authentication Features
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/OAuth2AuthenticationProcessingException.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/JwtAccessDeniedHandler.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/JwtAuthenticationEntryPoint.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/JwtAuthenticationFilter.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenDto.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2Provider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/OAuth2AuthenticationFailureHandler.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/GoogleOAuth2UserInfo.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/KakaoOAuth2UserInfo.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/OAuth2UserInfo.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/OAuth2UserInfoFactory.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/AgeGroup.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/Gender.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/Role.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/User.java
  matgpt/src/main/java/com/ktc/matgpt/user/repository/UserRepository.java
  matgpt/src/main/java/com/ktc/matgpt/utils/ApiUtils.java
  matgpt/src/main/java/com/ktc/matgpt/utils/CookieUtils.java
  matgpt/src/main/resources/application.yml
Labels: Setting, Feature, API

#25 Implementation of Review Create, Update, and Find Features
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/GlobalValidationHandler.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/exception/Exception400.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/exception/Exception401.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/exception/Exception403.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/exception/Exception404.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/errors/exception/Exception500.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/Image.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/PriceRange.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Config.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/utils/ApiUtils.java
  matgpt/src/main/resources/application.yml
Labels: Feature, API

#24 Feature/store
  matgpt/.gitignore
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/Category.java
Labels: Feature, API

#30 Implementation of Review Find with Pagination and Review Delete
  matgpt/src/main/java/com/ktc/matgpt/config/MessageConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/BaseTimeEntity.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStore.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/resources/messages.properties
  matgpt/src/main/resources/messages_en_US.properties
  matgpt/src/main/resources/messages_ko_KR.properties
Labels: Feature, Refactor

#32 Refactor Security Configurations and User Authentication in JWT Token Management
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
Labels: Refactor

#35 [6주차 제출] Weekly 로의 Merge
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
Labels: Submit

#31 Feature: store 추가기능( paging, filter) 구현 / Test Code 작성
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
Labels: Feature, API, Test

#37 [6주차 제출] feature/store -> Weekly
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
Labels: Submit

#38 [6주차 제출] Weekly -> Develop
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/MessageConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/BaseTimeEntity.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStore.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
  matgpt/src/main/resources/messages.properties
  matgpt/src/main/resources/messages_en_US.properties
  matgpt/src/main/resources/messages_ko_KR.properties
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
Labels: Submit

#39 [6주차 제출] Develop -> Master
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/MessageConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/BaseTimeEntity.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStore.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
  matgpt/src/main/resources/messages.properties
  matgpt/src/main/resources/messages_en_US.properties
  matgpt/src/main/resources/messages_ko_KR.properties
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
Labels: Submit

#45 Enchancement user authentication claims and Add test code
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Bugfix, Feature, Test

#46 [7주차 제출] feature/oauth-user -> Weekly
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Submit

#50 Implementation and Update of Store Searching with Sorting Option and Main Page Stores
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/Category.java
Labels: Feature, API, invalid

#40 부산대_4조_MatGPT_6주차
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/MessageConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/BaseTimeEntity.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStore.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/store/MockStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/controller/UserController.java
  matgpt/src/main/resources/messages.properties
  matgpt/src/main/resources/messages_en_US.properties
  matgpt/src/main/resources/messages_ko_KR.properties
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
Labels: Request Review

#54 Configuration For Swagger-UI & Update GPT Service Logics
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/CountryToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/ReviewsToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/MockReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/ReviewFactory.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptGuidanceRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptReviewRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/custom.sql
Labels: Feature, API

#51 Implementation of Adding Heart to Particular Store
  matgpt/src/main/java/com/ktc/matgpt/heart/storeHeart/Heart.java
  matgpt/src/main/java/com/ktc/matgpt/heart/storeHeart/HeartJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/heart/storeHeart/HeartResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/heart/storeHeart/HeartRestController.java
  matgpt/src/main/java/com/ktc/matgpt/heart/storeHeart/HeartService.java
Labels: Feature, API

#58 Fix conflict Resolution and delete duplicate code
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/Category.java
Labels: Bugfix

#59 [7주차 제출] feature/store-> Weekly
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/Category.java
Labels: Submit

#60 [7주차 제출] Weekly -> Develop
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/CountryToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/ReviewsToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/MockReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/ReviewFactory.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptGuidanceRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptReviewRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/config/DatabaseInitializer.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception400.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception403.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception404.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception500.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalValidationHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/SubCategory.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/application.yml
  matgpt/src/main/resources/custom.sql
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Submit

#63 [7주차 제출] Develop -> Master
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/CountryToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/ReviewsToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/MockReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/ReviewFactory.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptGuidanceRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptReviewRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/config/DatabaseInitializer.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception400.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception403.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception404.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception500.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalValidationHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/SubCategory.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/application.yml
  matgpt/src/main/resources/custom.sql
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Submit

#65 Bugfix: make code executable
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
Labels: Bugfix

#66 Update feature/heart branch
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
Labels: Git

#68 Implementation and Optimization of the "LikeStore" Feature
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStore.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/test/java/com/ktc/matgpt/likeStore/LikeStoreRestControllerTest.java
Labels: Bugfix, Feature, Refactor

#74 Enhancements and Refactor in Heart ("Like") and Food Management Features
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodController.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/food/dto/FoodDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeStore/LikeStore.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/utils/BaseTimeEntity.java
Labels: Feature, Refactor

#75 Enhanced Modularization and Refactoring of Image, Tag, Review, and S3 Logic
  matgpt/src/main/java/com/ktc/matgpt/aws/S3Config.java
  matgpt/src/main/java/com/ktc/matgpt/aws/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/food/dto/FoodDTO.java
  matgpt/src/main/java/com/ktc/matgpt/image/Image.java
  matgpt/src/main/java/com/ktc/matgpt/image/ImageJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/PriceRange.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/tag/TagJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/tag/TagService.java
Labels: Feature, API, Refactor, Need Test Code

#77 Refactor API Request with Webflux to Async & RestTemplate
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/config/AsyncConfig.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/config/RestTemplateConfig.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/config/WebClientConfig.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/FinishReason.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequest.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptResponse.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/resources/custom.sql
Labels: Feature, Refactor

#81 Refactor & Improve ChatGPT Services
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptApiRequest.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptApiResponse.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptResponse.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/utils/UnixTimeConverter.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/resources/custom.sql
Labels: Feature, Refactor

#83 Implement of User Based Recommendation and Store Marker
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/custom.sql
Labels: Feature, API

#86 Feature/store -> Weekly
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/custom.sql
Labels: Submit

#67 부산대_4조_MatGPT_7주차
  matgpt/build.gradle
  matgpt/src/main/java/com/ktc/matgpt/MatgptApplication.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/CountryToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/ReviewsToGptRequestConverter.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptGuidance.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/entity/GptReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/MockReview.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/factory/ReviewFactory.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptGuidanceRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/repository/GptReviewRepository.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/config/DatabaseInitializer.java
  matgpt/src/main/java/com/ktc/matgpt/config/SecurityConfig.java
  matgpt/src/main/java/com/ktc/matgpt/config/SwaggerConfig.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception400.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception403.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception404.java
  matgpt/src/main/java/com/ktc/matgpt/exception/Exception500.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalValidationHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/Food.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/food/FoodService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/s3/S3Service.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/Tag.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/security/UserPrincipal.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/store/entity/SubCategory.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/resources/application-dev.yml
  matgpt/src/main/resources/application-test.yml
  matgpt/src/main/resources/application.yml
  matgpt/src/main/resources/custom.sql
  matgpt/src/test/java/com/ktc/matgpt/store/StoreRestControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/user/controller/UserControllerTest.java
Labels: Request Review

#90 Renewal of Cursor-Based Pagination
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreRestController.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreService.java
  matgpt/src/main/java/com/ktc/matgpt/user/repository/UserRepository.java
  matgpt/src/main/java/com/ktc/matgpt/user/service/UserService.java
  matgpt/src/main/java/com/ktc/matgpt/utils/CursorRequest.java
  matgpt/src/main/java/com/ktc/matgpt/utils/PageResponse.java
Labels: Bugfix, Feature, Refactor

#91 Update GptResponse Contents
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/controller/GptRestController.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/dto/GptResponseDto.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/schedule/ScheduledTasks.java
  matgpt/src/main/java/com/ktc/matgpt/chatgpt/service/GptService.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
Labels: API, Refactor

#92 Improve review API and associated test codes
  matgpt/src/main/java/com/ktc/matgpt/image/ImageService.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReview.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewJPARepository.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewResponseDTO.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewService.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewRequest.java
  matgpt/src/main/java/com/ktc/matgpt/review/dto/ReviewResponse.java
  matgpt/src/main/java/com/ktc/matgpt/review/entity/Review.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/store/Store.java
  matgpt/src/main/java/com/ktc/matgpt/store/StoreResponse.java
  matgpt/src/main/java/com/ktc/matgpt/tag/TagService.java
  matgpt/src/main/java/com/ktc/matgpt/user/entity/User.java
  matgpt/src/main/resources/custom.sql
  matgpt/src/main/resources/images/image1.png
  matgpt/src/main/resources/images/image2.png
  matgpt/src/test/java/com/ktc/matgpt/TestHelper.java
  matgpt/src/test/java/com/ktc/matgpt/mypage/MyPageControllerTest.java
  matgpt/src/test/java/com/ktc/matgpt/review/ReviewRestControllerTest.java
Labels: Test, Refactor

#93 Integrating exception handling codes and Refactoring existing custom exception handling
  matgpt/src/main/java/com/ktc/matgpt/exception/ErrorCode.java
  matgpt/src/main/java/com/ktc/matgpt/exception/GlobalExceptionHandler.java
  matgpt/src/main/java/com/ktc/matgpt/exception/InvalidTokenException.java
  matgpt/src/main/java/com/ktc/matgpt/exception/OAuth2AuthenticationProcessingException.java
  matgpt/src/main/java/com/ktc/matgpt/feature_review/utils/ApiUtils.java
  matgpt/src/main/java/com/ktc/matgpt/like/likeReview/LikeReview.java
  matgpt/src/main/java/com/ktc/matgpt/review/ReviewRestController.java
  matgpt/src/main/java/com/ktc/matgpt/review/mypage/MyPageController.java
  matgpt/src/main/java/com/ktc/matgpt/security/jwt/TokenProvider.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/MatgptOAuth2UserService.java
  matgpt/src/main/java/com/ktc/matgpt/security/oauth2/userInfo/OAuth2UserInfoFactory.java
Labels: Bugfix, Refactor
